inicializacao:
	pip install --user -r requirements.txt
	python3 -m venv eEDB011_assignment_3_grupo_9
	python3 -m ipykernel install --user --name=eEDB011_assignment_3_grupo_9
	. eEDB011_assignment_3_grupo_9/bin/activate; pip install -r requirements.txt